Repository FOSS-UCSC/FOSSALGO, pull requests merged in 2020-09, with the labels that each got.

#55 SAG4X-Linear search,Binary Search in [C]
  .bin/install_apt.sh
  .bin/install_go.sh
  .bin/install_npm.sh
  .bin/install_pip2.sh
  .bin/install_pip3.sh
  .bin/test_running.sh
  .coafile
  .codeclimate.yml
  .editorconfig
  .gitignore
  .travis.yml
  README.md
  binary_search/README.md
  binary_search/binary_search.c
  linear_search/README.md
  linear_search/linear_search.c
  selection_sort/README.md
  selection_sort/selection_sort.c
Labels: SAG4X

#75 {Insertion Sort}{Modify a loop and remove unused code}-{TrojanX}
  insertion_sort/InsertionSort.java
  selection_sort/SelectionSort.java
Labels: not-qualified

#76 {Queue}{improve code and create commandline interface}-{TrojanX}
  binary_search_tree/binary_search_tree.py
  queue/Queue.py
  stack/stack.py
Labels: TrojanX

#91 {Linked List implement}{[C]}{coderSquad}
  linked_list/LinkedList.c
Labels: coderSquad

#92 Implement binary search in C
  binary_search_tree/Binarysearch.c
Labels: Team src

#104 Dev mergesort
  linked_list/linked_list.py
  merge_sort/mergesort.py
  queue/Queue.c
  selection_sort/selection_sort.py
Labels: Lemonade

#113 BlackHats
  shell_sort/shell_sort.cpp
Labels: BlackHats

#115 Merge sort in c language - {slayers}
  merge_sort/mergesort.c
Labels: Slayers

#119 Create doubly_linked_list.c
  bubble_sort/bubble_sort.py
  doubly_linked_list/doubly_linked_list.c
Labels: Team Titans

#121 Dev stack
  binary_search_tree/BST.java
  stack/Stack in C
Labels: Team Code Builders

#127 insertion sort update
  insertion_sort/insertionsort.c
Labels: Slayers

#131 TeamX001
  doubly_linked_list/DLL.c
  insertion_sort/j11.txt
Labels: TeamX001

#133 SAG4X - added stack in[c]
  breadth_first_search/README.txt
  stack/README.md
  stack/stack.c
Labels: SAG4X

#241 SAG4X - added Queue in [Java]
  breadth_first_search/README.txt
  stack/README.md
  stack/stack.c
Labels: SAG4X

#134 Team Code Builders-Stack Implementation in c
  selection_sort/selection_sort
  stack/Stack linked list
Labels: Team Code Builders

#136 Team Code Builders-Queue Implementation in c
  queue/queue in c
Labels: Team Code Builders

#137 Team Code Builders-Binary Search Tree Implementation in c
  binary_search/Binary_Search
  binary_search/Binary_Search[C++]
  binary_search_tree/Binary Search Tree
Labels: Team Code Builders

#155 {Binary Search }{[Java]}{coderSquad}
  binary_search/BinarySearch.java
Labels: coderSquad

#203 {Doubly Linked List Implementation }{[C]}{coderSquad}
  doubly_linked_list/DoublyLinkedList.c
Labels: coderSquad

#237 Team Code Builders - Double Linked List
  doubly_linked_list/doubleLimkedList.c
Labels: Team Code Builders

#128 Queue algorithm{X-Team}
  insertion_sort/insertionSort.c
  queue/newqueue.c
Labels: X-Team

#248 Team-X001, Queue Implementation done in java(Dynamically)
  queue/Demo.java
Labels: TeamX001

#252 SAG4X-Linked list queue in [C]
  linked_list/README.md
  linked_list/linked_list_queue.c
Labels: SAG4X

#270 {Queue Implementation}{[Java]}{coderSquad}
  queue/Queue.java
Labels: coderSquad

#321 stack in c
  .vscode/c_cpp_properties.json
  binary_search/BinarySearch.c
  insertion.c
  linked_list/Linked list.c
  stack/Stack.c
Labels: Smash Code
