Repository FOSS-UCSC/FOSSALGO, pull requests merged in 2020-10, with the labels that each got.

#383 Added the binary search algorithm in javascript
  README.md
  algorithms/ar-bsrh/javascript/binary_search.js
Labels: completed, waiting-for-documentation

#413 Added Bubble Sort in JavaScript
  README.md
  algorithms/ar-bsrt/javascript/bubble_sort.js
Labels: hacktoberfest-accepted

#391 Added binarysearch in python2
  README.md
  algorithms/ar-bsrh/python2/binary_search.py
Labels: hacktoberfest-accepted

#423 Added Quick Sort Implementation in C
  README.md
  algorithms/ar-qsrt/c/quick_sort.c
Labels: hacktoberfest-accepted

#422 added implementation of stack in CPP
  README.md
  data-structures/ds-stk/cpp/stack.cpp
Labels: hacktoberfest-accepted

#417 Added MergeSort with GoLang
  README.md
  algorithms/ar-msrt/golang/merge_sort.go
Labels: completed, hacktoberfest-accepted, waiting-for-documentation

#439 Added BinSort.java
  README.md
  algorithms/ar-binsrt/java/BinSort.java
Labels: completed, hacktoberfest-accepted

#445 Bin-Sort in Python
  README.md
  algorithms/ar-binsrt/python3/binsrt.py
Labels: completed, hacktoberfest-accepted

#449 Added simple documentation for bubble sort algorithm
  algorithms/ar-bsrt/README.md
Labels: completed, hacktoberfest-accepted

#453 essential updates for the system
  .all-contributorsrc
  CONTRIBUTING.md
  README.md
  algorithms/ar-lsrh/java/LinearSearch.java
  data-structures/ds-slinklst/java/LinkedList.java
Labels: system-testing

#450 Adding Binary Sort Algorithm in JavaScript
  README.md
  algorithms/ar-binsrt/javascript/binary_sort.js
Labels: completed, hacktoberfest-accepted

#454 Added simple documentation for binary search algorithm
  algorithms/ar-bsrh/README.md
Labels: completed, hacktoberfest-accepted

#469 added breadth first search in python3
  README.md
  algorithms/gr-bfsrh/python3/breadth_first_search.py
Labels: hacktoberfest-accepted

#473 Added insertion sort in Go
  algorithms/ar-isrt/golang/insertion_sort.go
Labels: completed, hacktoberfest-accepted

#483 Bin-Sort in C
  README.md
  algorithms/ar-binsrt/c/binsrt.c
Labels: completed, hacktoberfest-accepted

#496 implement shell sort in python3
  README.md
  algorithms/ar-shsrt/python3/shell_sort.py
Labels: hacktoberfest-accepted

#506 Added DFS Graph Algorithm in C
  README.md
  algorithms/gr-dfsrh/c/depth_first_search.c
Labels: hacktoberfest-accepted

#508 Added DFS Graph Algorithm in C++
  README.md
  algorithms/gr-dfsrh/cpp/depth_first_search.cpp
Labels: hacktoberfest-accepted

#512 Added Bubble Sort in TypeScript
  README.md
  algorithms/ar-bsrt/typescript/bubble_sort.ts
Labels: completed, hacktoberfest-accepted

#539 implement stack in java
  README.md
  data-structures/ds-stk/java/Stack.java
Labels: completed, hacktoberfest-accepted

#547 Added Prime Factors in Python 3
  README.md
  algorithms/ar-prfac/python3/prime_factor.py
Labels: completed, hacktoberfest-accepted

#555 Added merge sort in Javascript
  README.md
  algorithms/ar-msrt/javascript/merge_sort.js
Labels: hacktoberfest-accepted

#563 Added Dijkstra Algorithm in C++
  README.md
  algorithms/gr-dij/cpp/dijkstra_algorithm.cpp
Labels: hacktoberfest-accepted

#562 Added Circular Queue In C
  README.md
  data-structures/ds-cque/c/circular_queue.c
Labels: hacktoberfest-accepted

#561 Added merge sort in Typescript
  README.md
  algorithms/ar-msrt/typescript/merge_sort.ts
Labels: hacktoberfest-accepted

#576 Adding modular exponential in Typescript
  README.md
  algorithms/ar-mexp/typescript/modular_exponential.ts
Labels: completed, hacktoberfest-accepted

#583 Added Bin-Sort algorithm for C# from Issue#432
  README.md
  algorithms/ar-binsrt/csharp/BinSort.cs
Labels: completed, hacktoberfest-accepted, waiting-for-documentation

#580 Added Breadth First Search in Typescript
  README.md
  algorithms/gr-bfsrh/typescript/breadth_first_search.ts
Labels: completed, hacktoberfest-accepted, waiting-for-documentation

#586 Added CoinChange.java
  README.md
  algorithms/ar-cochprb/java/CoinChange.java
Labels: completed, hacktoberfest-accepted, waiting-for-documentation

#513 Added Depth First Search in Typescript
  README.md
  algorithms/gr-dfsrh/typescript/depth_first_search.ts
Labels: completed, hacktoberfest-accepted, waiting-for-documentation

#589 add coin change problem in c language
  README.md
  algorithms/ar-cochprb/c/coin_change_problem.c
Labels: completed, hacktoberfest-accepted

#608 Adding modular exponential in javascript
  README.md
  algorithms/ar-mexp/javascript/modular_exponential.js
Labels: completed, hacktoberfest-accepted

#595 Add bubble sort in charp to readme as well
  README.md
  algorithms/ar-bsrt/csharp/BubbleSort.cs
Labels: need-changes

#594 Added Radix Sort in C++ #592
  README.md
  algorithms/ar-radsrt/cpp/radix_sort.cpp
Labels: hacktoberfest-accepted

#593 Added Dijkstra Algorithm [C]
  README.md
  algorithms/gr-dij/c/dijkstra_algorithm.c
Labels: hacktoberfest-accepted

#617 Added exponetiation by squaring algorithm in javascript
  README.md
  algorithms/ar-expsq/javascript/exponentiation_by_squaring.js
Labels: completed, hacktoberfest-accepted

#558 Added Priority Queue #556
  README.md
  data-structures/ds-pque/java/PriorityQueue.java
Labels: completed, hacktoberfest-accepted

#622 Added Dijkstra Algorithm in Python3
  README.md
  algorithms/gr-dij/python3/dijkstra.py
Labels: hacktoberfest-accepted, waiting-for-documentation

#621 Create C# implementation of Exponentiation using Squaring
  README.md
  algorithms/ar-expsq/csharp/ExponentiationBySquaring.cs
Labels: hacktoberfest-accepted, waiting-for-documentation

#641 coin change added in GoLang.
  README.md
  algorithms/ar-cochprb/golang/coin_change.go
Labels: completed, hacktoberfest-accepted

#656 Exponentiation with squaring implemented in Python3
  README.md
  algorithms/ar-expsq/python3/exponentiation_by_squaring.py
Labels: hacktoberfest-accepted, waiting-for-documentation

#642 Added Insertion Sort in C#
  README.md
  algorithms/ar-isrt/csharp/InsertionSort.cs
Labels: hacktoberfest-accepted, waiting-for-documentation

#663 Added Insertion Sort Python 3
  README.md
  algorithms/ar-isrt/python3/insertion_sort.py
Labels: hacktoberfest-accepted, waiting-for-documentation

#671 Added exponentiation by squaring algorithm in C
  README.md
  algorithms/ar-expsq/c/exponentiation_by_squaring.c
Labels: completed, hacktoberfest-accepted

#645 added typescript insertion_sort algorithm
  README.md
  algorithms/ar-isrt/typescript/insertion_sort.ts
Labels: completed, hacktoberfest-accepted

#673 Implement heap sort in C#
  README.md
  algorithms/ar-hsrt/csharp/HeapSort.cs
Labels: completed, hacktoberfest-accepted

#695 Sleep sort in C
  README.md
  algorithms/ar-slpsrt/c/ar_slpsrt.c
Labels: completed, hacktoberfest-accepted

#698 Added Knuth Morris Pratt in C++
  README.md
  algorithms/ar-kmp/cpp/knuth_morris_pratt.cpp
Labels: completed, hacktoberfest-accepted

#676 Added Circular Queue in Java
  README.md
  data-structures/ds-cque/java/CircularQueue.java
Labels: completed, hacktoberfest-accepted

#717 Heap Sort Typescript Implementation
  README.md
  algorithms/ar-hsrt/typescript/heap_sort.ts
Labels: completed, hacktoberfest-accepted

#707 Added Sieve of Eratosthenes Algorithm
  README.md
  algorithms/ar-soer/java/SieveOfEratosthenes.java
Labels: completed, hacktoberfest-accepted

#721 Added Queue in Typescript
  README.md
  data-structures/ds-que/typescript/queue.ts
Labels: completed, hacktoberfest-accepted

#722 Create implementation.c
  README.md
  data-structures/ds-dlinklst/c/implementation.c
Labels: hacktoberfest-accepted, waiting-for-documentation

#677 Added dijkstra_algorithm.js
  algorithms/gr-dij/README.md
  algorithms/gr-dij/javascript/dijkstra_algorithm.js
Labels: hacktoberfest-accepted, waiting-for-documentation

#742 linear regression for python3
  README.md
  algorithms/ar-lreg/python3/linear_regression.py
Labels: completed, hacktoberfest-accepted

#743 Knn in c
  algorithms/ar-knn/c/knn.c
  algorithms/ar-slpsrt/c/ar_slpsrt.c
Labels: completed, hacktoberfest-accepted

#746 Add Largest Sum Contiguous Subarray in Go
  README.md
  algorithms/ar-lscsa/golang/largest_sum_contiguous_subarray.go
Labels: completed, hacktoberfest-accepted

#747 Added Linear Regression Javascript
  README.md
  algorithms/ar-lreg/javascript/linear_regression.js
Labels: completed, hacktoberfest-accepted

#748 Add Largest Sum Contiguous Subarray in CSharp
  README.md
  algorithms/ar-lscsa/csharp/LargestSumContiguousSubArray.cs
Labels: completed, hacktoberfest-accepted

#751 Linear Regression in C
  README.md
  algorithms/ar-lreg/c/linear_regression.c
Labels: completed, hacktoberfest-accepted

#753 Add Depth First Search in Golang
  README.md
  algorithms/gr-dfsrh/golang/dfsrh.go
Labels: completed, hacktoberfest-accepted

#752 Added Linear Regression in Typescript
  README.md
  algorithms/ar-lreg/typescript/linear_regression.ts
Labels: completed, hacktoberfest-accepted

#764 Add Sleep Sort implementation for Java
  README.md
  algorithms/ar-slpsrt/java/SleepSort.java
Labels: completed, hacktoberfest-accepted

#767 Add Shell Sort implementation for Java
  README.md
  algorithms/ar-shsrt/java/ShellSort.java
Labels: completed, hacktoberfest-accepted

#768 Added Largest Sum Contiguous Subarray in Java
  README.md
  algorithms/ar-lscsa/java/LargestSumContiguousSubArray.java
Labels: completed, hacktoberfest-accepted

#770 Added Knuth-Morris-Pratt in TypeScript
  README.md
  algorithms/ar-kmp/typescript/knuth_morris_pratt.ts
Labels: completed, hacktoberfest-accepted

#769 Added Knuth-Morris-Pratt in Javascript
  README.md
  algorithms/ar-kmp/javascript/knuth_morris_pratt.js
Labels: completed, hacktoberfest-accepted

#788 Added Linear Search in Javascript
  README.md
  algorithms/ar-lsrh/javascript/linear_search.js
Labels: completed, hacktoberfest-accepted

#757 Added largest sum contiguous subarray code in C++
  README.md
  algorithms/ar-lscsa/cpp/largest_sum_contiguous_subarray.cpp
Labels: completed, hacktoberfest-accepted

#791 Added Depth First Search in Javascript
  README.md
  algorithms/gr-dfsrh/javascript/dfs.js
Labels: completed, hacktoberfest-accepted

#794 Added linear search [Go]
  README.md
  algorithms/ar-lsrh/golang/linear_search.go
Labels: completed, hacktoberfest-accepted

#789 max sum array
  README.md
  algorithms/ar-lscsa/python3/max_sum_array.py
Labels: completed, hacktoberfest-accepted

#795 linear_search
  README.md
  algorithms/ar-lsrh/cpp/linear_search.cpp
Labels: completed, hacktoberfest-accepted

#800 Added Depth First Search in Java
  README.md
  algorithms/gr-dfsrh/java/DepthFirstSearch.java
Labels: completed, hacktoberfest-accepted

#799 Linear Regression in C++. #733
  README.md
  algorithms/ar-lreg/cpp/linear_regression.cpp
Labels: completed, hacktoberfest-accepted

#804 Added Breadth First Search in Java
  README.md
  algorithms/gr-bfsrh/java/BreadthFirstSearch.java
Labels: completed, hacktoberfest-accepted

#809 Mergesortcpp
  README.md
  algorithms/ar-msrt/cpp/merge_sort.cpp
Labels: completed, hacktoberfest-accepted

#803 added lcs in python3
  README.md
  algorithms/ar-lcs/python3/longest_common_subsequence.py
Labels: completed, hacktoberfest-accepted

#828 Added Coin Change Problem in C#
  README.md
  algorithms/ar-cochprb/csharp/CoinChangeProblem.cs
Labels: completed, hacktoberfest-accepted

#825 Added longest increasing subsequence in Python3 (Issue #820)
  README.md
  algorithms/ar-lis/python3/longest_increasing_subsequence.py
Labels: completed, hacktoberfest-accepted
